name: MoreFish
version: 2.0.0
author: elsiff
website: http://elsiff.me
main: me.elsiff.morefish.MoreFish
softdepend: [Vault, Citizens]
commands:
  morefish:
    description: Main command for MoreFish.
    usage: /morefish
    aliases: [mf, fish]
permissions:
  morefish.admin:
    default: op
    description: Give user ability to control the fishing contest.
  morefish.top:
    default: true
    description: Player with this permission can use /morefish top command.
  morefish.shop:
    default: op
    description: Player with this permission can use /morefish shop command.